export const SITE_CONFIG = {
  name: "PT Jasa Mandiri Agency",
  legalName: "PT Jasa Mandiri Agency",
  shortName: "Jasa Mandiri Agency",
  url: "https://pekerjarumahtangga.com",
  domain: "pekerjarumahtangga.com",
  logo: "https://pekerjarumahtangga.com/logo.png",
  image: "https://pekerjarumahtangga.com/logo.png",
  telephone: "+6285111399962",
  whatsappPrimary: "08818009992",
  whatsappSecondary: "08119119996",
  email: "info@pekerjarumahtangga.com",
  foundingDate: "2010",
  legalStatus: "Perusahaan Penempatan Pekerja Rumah Tangga (P3RT) & LPK Resmi Disnaker Kemnaker RI",
  priceRange: "Rp 2.500.000 - Rp 5.500.000",
  address: {
    streetAddress: "Jl. Gunung Balong III No.78, RT.11/RW.4",
    addressLocality: "Lebak bulus, Cilandak, Jakarta Selatan",
    addressRegion: "DKI Jakarta",
    postalCode: "12440",
    addressCountry: "ID",
  },
  geo: {
    latitude: -6.3047534,
    longitude: 106.7884377,
  },
  openingHours: "Mo-Su 08:00-21:00",
  openingHoursFormatted: "Senin - Minggu: 08:00 - 21:00 WIB",
  social: [
    "https://www.instagram.com/cvjasamandiri",
    "https://www.facebook.com/jasa.mandiri.penyalurkerja/",
    "https://www.tiktok.com/@baby.sitterku",
  ],
};
