-- SQL Migration script to create Pekerja, Artikel, and Master Keahlian tables in Supabase

-- 1. Create table pekerja
CREATE TABLE IF NOT EXISTS public.pekerja (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  kategori TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Tersedia',
  pengalaman INT DEFAULT 0,
  gaji NUMERIC DEFAULT 0,
  "fotoUrl" TEXT,
  foto_url TEXT,
  lokasi TEXT DEFAULT 'Jakarta',
  deskripsi TEXT,
  keterampilan TEXT,
  umur INT,
  suku TEXT,
  kekurangan TEXT,
  bisa_bawa_motor BOOLEAN DEFAULT FALSE,
  takut_anjing BOOLEAN DEFAULT FALSE,
  status_perkawinan TEXT,
  keahlian_khusus TEXT,
  agama TEXT,
  bahasa_asing TEXT[],
  bisa_masak_babi BOOLEAN DEFAULT FALSE,
  masakan_khusus TEXT,
  pendidikan_terakhir TEXT,
  tinggi_badan INT,
  berat_badan INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create table artikel
CREATE TABLE IF NOT EXISTS public.artikel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  konten TEXT NOT NULL,
  gambar_url TEXT,
  alt_gambar TEXT,
  meta_title TEXT,
  meta_description TEXT,
  focus_keyword TEXT,
  secondary_keyword TEXT,
  kategori BOOLEAN DEFAULT TRUE, -- TRUE = Published, FALSE = Draft
  views BIGINT DEFAULT 0,
  tags TEXT,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration for existing artikel table
ALTER TABLE public.artikel ADD COLUMN IF NOT EXISTS alt_gambar TEXT;
ALTER TABLE public.artikel ADD COLUMN IF NOT EXISTS meta_title TEXT;
ALTER TABLE public.artikel ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE public.artikel ADD COLUMN IF NOT EXISTS focus_keyword TEXT;
ALTER TABLE public.artikel ADD COLUMN IF NOT EXISTS secondary_keyword TEXT;

-- 3. Create table master_keahlian
CREATE TABLE IF NOT EXISTS public.master_keahlian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_keahlian TEXT UNIQUE NOT NULL,
  kategori_keahlian TEXT NOT NULL DEFAULT 'Umum',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Seed initial skills into master_keahlian
INSERT INTO public.master_keahlian (nama_keahlian, kategori_keahlian) VALUES
  ('Memasak Makanan Indonesia', 'Asisten Rumah Tangga'),
  ('Mencuci & Menyetrika Rapi', 'Asisten Rumah Tangga'),
  ('Membersihkan Rumah (Deep Cleaning)', 'Asisten Rumah Tangga'),
  ('Mengoperasikan Mesin Cuci', 'Asisten Rumah Tangga'),
  ('Mengurus Tanaman / Kebun', 'Asisten Rumah Tangga'),
  ('Mengasuh Anak Kecil (Bantu)', 'Asisten Rumah Tangga'),
  ('Mengurus Hewan Peliharaan', 'Asisten Rumah Tangga'),
  ('Memandikan Bayi Baru Lahir (Newborn)', 'Baby Sitter'),
  ('Membuat & Sterilisasi Botol Susu', 'Baby Sitter'),
  ('Menyiapkan MPASI Sehat', 'Baby Sitter'),
  ('Menstimulasi Tumbuh Kembang Anak', 'Baby Sitter'),
  ('Pendampingan Belajar Anak', 'Baby Sitter'),
  ('Pertolongan Pertama Bayi / Anak', 'Baby Sitter'),
  ('Menidurkan & Menjaga Tidur Bayi', 'Baby Sitter'),
  ('Merawat Lansia Bedridden (Tirah Baring)', 'Perawat Lansia'),
  ('Mendampingi Aktivitas Harian Lansia', 'Perawat Lansia'),
  ('Menyiapkan Makanan & Obat Sesuai Jadwal', 'Perawat Lansia'),
  ('Mengukur Tensi & Gula Darah', 'Perawat Lansia'),
  ('Membantu Fisioterapi Ringan / Jalan', 'Perawat Lansia'),
  ('Memandikan Lansia Menggunakan Kursi Roda', 'Perawat Lansia'),
  ('Sabar & Menangani Demensia / Alzheimer', 'Perawat Lansia'),
  ('Mengemudikan Mobil Transmisi Manual & Matic', 'Supir'),
  ('Memahami Rute Jabodetabek & Tol', 'Supir'),
  ('Perawatan & Kebersihan Kendaraan', 'Supir'),
  ('Disiplin Waktu & Mengutamakan Keselamatan', 'Supir'),
  ('Pemangkasan & Perapian Tanaman', 'Tukang Kebun'),
  ('Pemupukan & Pemeliharaan Tanah', 'Tukang Kebun'),
  ('Pembersihan Area Halaman & Taman', 'Tukang Kebun')
ON CONFLICT (nama_keahlian) DO NOTHING;

-- 5. Enable RLS and allow public read access, authenticated write access
ALTER TABLE public.pekerja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artikel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_keahlian ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on pekerja" ON public.pekerja;
DROP POLICY IF EXISTS "Allow public write access on pekerja" ON public.pekerja;
CREATE POLICY "Allow public read access on pekerja" ON public.pekerja FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert on pekerja" ON public.pekerja FOR INSERT TO authenticated WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on pekerja" ON public.pekerja FOR UPDATE TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on pekerja" ON public.pekerja FOR DELETE TO authenticated USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow public read access on artikel" ON public.artikel;
DROP POLICY IF EXISTS "Allow public write access on artikel" ON public.artikel;
CREATE POLICY "Allow public read access on artikel" ON public.artikel FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert on artikel" ON public.artikel FOR INSERT TO authenticated WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on artikel" ON public.artikel FOR UPDATE TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on artikel" ON public.artikel FOR DELETE TO authenticated USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow public read access on master_keahlian" ON public.master_keahlian;
DROP POLICY IF EXISTS "Allow public write access on master_keahlian" ON public.master_keahlian;
CREATE POLICY "Allow public read access on master_keahlian" ON public.master_keahlian FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert on master_keahlian" ON public.master_keahlian FOR INSERT TO authenticated WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on master_keahlian" ON public.master_keahlian FOR UPDATE TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on master_keahlian" ON public.master_keahlian FOR DELETE TO authenticated USING (auth.role() = 'authenticated');

-- 6. Storage Buckets Setup & Storage RLS Policies
INSERT INTO storage.buckets (id, name, public)
VALUES ('foto-pekerja', 'foto-pekerja', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public)
VALUES ('artikel-gambar', 'artikel-gambar', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public)
VALUES ('gambar-artikel', 'gambar-artikel', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies for 'foto-pekerja' bucket
DROP POLICY IF EXISTS "Public Read Access for foto-pekerja" ON storage.objects;
CREATE POLICY "Public Read Access for foto-pekerja"
ON storage.objects FOR SELECT
USING (bucket_id = 'foto-pekerja');

DROP POLICY IF EXISTS "Authenticated Upload Access for foto-pekerja" ON storage.objects;
CREATE POLICY "Authenticated Upload Access for foto-pekerja"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'foto-pekerja' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated Update Access for foto-pekerja" ON storage.objects;
CREATE POLICY "Authenticated Update Access for foto-pekerja"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'foto-pekerja' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated Delete Access for foto-pekerja" ON storage.objects;
CREATE POLICY "Authenticated Delete Access for foto-pekerja"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'foto-pekerja' AND auth.role() = 'authenticated');

-- Storage Policies for 'artikel-gambar' / 'gambar-artikel' bucket
DROP POLICY IF EXISTS "Public Read Access for artikel-gambar" ON storage.objects;
CREATE POLICY "Public Read Access for artikel-gambar"
ON storage.objects FOR SELECT
USING (bucket_id = 'artikel-gambar' OR bucket_id = 'gambar-artikel');

DROP POLICY IF EXISTS "Authenticated Upload Access for artikel-gambar" ON storage.objects;
CREATE POLICY "Authenticated Upload Access for artikel-gambar"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK ((bucket_id = 'artikel-gambar' OR bucket_id = 'gambar-artikel') AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated Update Access for artikel-gambar" ON storage.objects;
CREATE POLICY "Authenticated Update Access for artikel-gambar"
ON storage.objects FOR UPDATE TO authenticated
USING ((bucket_id = 'artikel-gambar' OR bucket_id = 'gambar-artikel') AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated Delete Access for artikel-gambar" ON storage.objects;
CREATE POLICY "Authenticated Delete Access for artikel-gambar"
ON storage.objects FOR DELETE TO authenticated
USING ((bucket_id = 'artikel-gambar' OR bucket_id = 'gambar-artikel') AND auth.role() = 'authenticated');

-- 7. Table site_settings (Global CMS Settings for Pages, Hero Images, and Company Identity)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on site_settings" ON public.site_settings;
DROP POLICY IF EXISTS "Allow public write access on site_settings" ON public.site_settings;
CREATE POLICY "Allow public read access on site_settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert on site_settings" ON public.site_settings FOR INSERT TO authenticated WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update on site_settings" ON public.site_settings FOR UPDATE TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete on site_settings" ON public.site_settings FOR DELETE TO authenticated USING (auth.role() = 'authenticated');

-- Seed initial default settings
INSERT INTO public.site_settings (id, name, data) VALUES
(
  'company_identity',
  'Identitas Perusahaan',
  '{
    "nama_perusahaan": "PT Jasa Mandiri",
    "tagline": "Penyalur Resmi Berizin Kemnaker & Disnaker sejak 2010",
    "subtagline": "Premium Domestic Care",
    "logo_url": "/logo-jm.webp",
    "favicon_url": "/logo-jm.webp",
    "nomor_whatsapp": "6285111399962",
    "nomor_telepon": "+62 851-1139-9962",
    "email": "info@pekerjarumahtangga.com",
    "alamat_lengkap": "Jl. Gunung Balong III No.78, RT.11/RW.4, Lb. Bulus, Kec. Cilandak, Kota Jakarta Selatan, DKI Jakarta 12440",
    "google_maps_url": "https://maps.app.goo.gl/z5f5F93TwLPZJA7n7",
    "jam_operasional": "Senin - Minggu: 08:00 - 21:00 WIB",
    "izin_kemnaker": "LPK No. 410/2010",
    "izin_disnaker": "Terdaftar DISNAKER & PJTKI",
    "deskripsi": "Penyalur resmi Asisten Rumah Tangga, Baby Sitter, dan Perawat Lansia berizin resmi Disnaker & Kemnaker sejak 2010. Mengutamakan kebersihan, etika, dan keamanan keluarga Anda."
  }'::jsonb
),
(
  'page_home',
  'Halaman Beranda',
  '{
    "meta_title": "PT Jasa Mandiri — Penempatan Pekerja Rumah Tangga Resmi & Terpercaya",
    "meta_description": "Penyalur resmi Asisten Rumah Tangga, Baby Sitter, dan Perawat Lansia berizin Disnaker & Kemnaker sejak 2010. Garansi penempatan resmi, rekam medis bersih, dan bebas biaya penukaran.",
    "keywords": "penyalur art jakarta, yayasan baby sitter terpercaya, perawat lansia jabodetabek, pembantu rumah tangga bergaransi",
    "og_image": "/asisten-rumah-tangga.webp",
    "hero_title": "Kenyamanan & Ketenangan Rumah Dimulai dari Tangan yang Tepat.",
    "hero_subtitle": "PT Jasa Mandiri menyalurkan Asisten Rumah Tangga, Baby Sitter, dan Perawat Lansia terpercaya yang telah melewati verifikasi identitas ketat, pemeriksaan kesehatan medis, serta pelatihan etika kerja profesional.",
    "hero_image": "/asisten-rumah-tangga.webp",
    "hero_image_alt": "Penyalur Asisten Rumah Tangga Resmi PT Jasa Mandiri",
    "service_art_image": "/asisten-rumah-tangga.webp",
    "service_babysitter_image": "/baby-sitter.webp",
    "service_perawat_image": "/perawat-lansia.webp"
  }'::jsonb
),
(
  'page_layanan',
  'Halaman Layanan Utama',
  '{
    "meta_title": "Layanan Penempatan PRT, Baby Sitter & Perawat Lansia Resmi | PT Jasa Mandiri",
    "meta_description": "Katalog resmi layanan PT Jasa Mandiri: penyalur PRT, Baby Sitter terdidik, dan Perawat Lansia profesional. Berizin resmi Disnaker, rekam medis bersih, dan garansi kontrak.",
    "keywords": "layanan penyalur tenaga kerja rumah tangga, yayasan prt baby sitter lansia resmi",
    "og_image": "/asisten-rumah-tangga.webp",
    "hero_title": "Solusi Tenaga Kerja Rumah Tangga Terpercaya & Profesional",
    "hero_subtitle": "Temukan tenaga kerja terlatih dan terverifikasi untuk mendukung kebersihan, kehangatan keluarga, dan kesehatan orang tercinta di rumah Anda."
  }'::jsonb
),
(
  'page_art',
  'Halaman Layanan ART',
  '{
    "meta_title": "Layanan Asisten Rumah Tangga (ART) Terlatih & Bergaransi | PT Jasa Mandiri",
    "meta_description": "Dapatkan tenaga ART terverifikasi dengan latar belakang bersih, uji kesehatan lengkap, serta etika kerja profesional untuk mendukung kelancaran aktivitas harian keluarga Anda.",
    "keywords": "jasa asisten rumah tangga, yayasan art jakarta, pembantu rumah tangga menginap, art pulang pergi",
    "og_image": "/asisten-rumah-tangga.webp",
    "hero_title": "Asisten Rumah Tangga Terlatih untuk Rumah yang Rapi, Bersih, dan Terawat.",
    "hero_subtitle": "Dapatkan tenaga ART terverifikasi dengan latar belakang bersih, uji kesehatan lengkap, serta etika kerja profesional untuk mendukung kelancaran aktivitas harian keluarga Anda.",
    "hero_image": "/asisten-rumah-tangga.webp",
    "hero_image_alt": "Layanan Asisten Rumah Tangga PT Jasa Mandiri"
  }'::jsonb
),
(
  'page_baby_sitter',
  'Halaman Layanan Baby Sitter',
  '{
    "meta_title": "Layanan Baby Sitter & Nanny Profesional Terpercaya | PT Jasa Mandiri",
    "meta_description": "Layanan baby sitter premium dengan standar operasional ketat, skrining berlapis, dan dedikasi penuh untuk menghadirkan ketenangan pikiran bagi orang tua di rumah.",
    "keywords": "baby sitter jakarta, pengasuh bayi newborn, yayasan suster anak resmi, nanny terdidik jabodetabek",
    "og_image": "/baby-sitter.webp",
    "hero_title": "Pengasuhan Penuh Kasih & Rasa Aman untuk Tumbuh Kembang Buah Hati Anda.",
    "hero_subtitle": "Layanan baby sitter premium dengan standar operasional ketat, skrining berlapis, dan dedikasi penuh untuk menghadirkan ketenangan pikiran bagi orang tua di rumah.",
    "hero_image": "/baby-sitter.webp",
    "hero_image_alt": "Layanan Baby Sitter Premium PT Jasa Mandiri"
  }'::jsonb
),
(
  'page_perawat_lansia',
  'Halaman Layanan Perawat Lansia',
  '{
    "meta_title": "Layanan Perawat Lansia & Caregiver Berpengalaman | PT Jasa Mandiri",
    "meta_description": "Dapatkan caregiver dan perawat lansia terseleksi yang sabar, teliti mengawal kebutuhan medis harian, serta hadir sebagai teman bicara yang memberikan kenyamanan emosional di rumah.",
    "keywords": "perawat lansia jakarta, caregiver orang tua, suster lansia bedridden, perawat lansia terpercaya",
    "og_image": "/perawat-lansia.webp",
    "hero_title": "Pendampingan Penuh Empati, Martabat, & Perhatian Tulus untuk Orang Tua Tercinta.",
    "hero_subtitle": "Dapatkan caregiver dan perawat lansia terseleksi yang sabar, teliti mengawal kebutuhan medis harian, serta hadir sebagai teman bicara yang memberikan kenyamanan emosional di rumah.",
    "hero_image": "/perawat-lansia.webp",
    "hero_image_alt": "Layanan Perawat Lansia PT Jasa Mandiri"
  }'::jsonb
),
(
  'page_tentang_kami',
  'Halaman Tentang Kami',
  '{
    "meta_title": "Tentang PT Jasa Mandiri | Penyalur Tenaga Kerja Rumah Tangga Resmi Sejak 2010",
    "meta_description": "Pelajari legalitas resmi, standar pelatihan, dan komitmen PT Jasa Mandiri dalam menyalurkan pekerja rumah tangga berkualitas tinggi di bawah payung hukum Kemnaker RI.",
    "keywords": "legalitas pt jasa mandiri, izin kemnaker p3rt, sejarah pt jasa mandiri, yayasan prt terdaftar",
    "og_image": "/asisten-rumah-tangga.webp",
    "hero_title": "Integritas, Legalitas, & Ketenangan Pikiran untuk Setiap Keluarga.",
    "hero_subtitle": "Sejak 2010, PT Jasa Mandiri berdedikasi menjembatani keluarga dengan pekerja domestik beretika, terlatih, dan berpayung hukum jelas."
  }'::jsonb
),
(
  'page_kontak',
  'Halaman Kontak',
  '{
    "meta_title": "Hubungi PT Jasa Mandiri | Kantor Penyalur PRT, Baby Sitter & Perawat Lansia",
    "meta_description": "Konsultasikan kebutuhan PRT, baby sitter, dan perawat lansia bersama PT Jasa Mandiri. Layanan cepat via WhatsApp atau kunjungi kantor operasional resmi kami.",
    "keywords": "kantor penyalur pembantu Jakarta, alamat yayasan babysitter resmi, kontak penyalur PRT terpercaya",
    "og_image": "/asisten-rumah-tangga.webp"
  }'::jsonb
),
(
  'page_pekerja',
  'Halaman Katalog Pekerja',
  '{
    "meta_title": "Katalog Pekerja Terverifikasi | ART, Baby Sitter & Perawat Lansia | PT Jasa Mandiri",
    "meta_description": "Penyalur resmi berizin Disnaker. Seluruh kandidat telah terverifikasi KTP, latar belakang, serta cek kesehatan berkala.",
    "keywords": "daftar pembantu siap kerja, cari baby sitter jakarta, lowongan suster lansia",
    "og_image": "/asisten-rumah-tangga.webp"
  }'::jsonb
),
(
  'page_artikel',
  'Halaman Blog Artikel',
  '{
    "meta_title": "Artikel & Edukasi Rumah Tangga | PT Jasa Mandiri",
    "meta_description": "Kumpulan tips, panduan hukum ketenagakerjaan rumah tangga, standar gaji PRT, dan panduan pengasuhan anak terpercaya dari tim ahli PT Jasa Mandiri.",
    "keywords": "tips memilih pembantu, standar gaji art 2026, panduan merawat lansia, artikel baby sitter",
    "og_image": "/asisten-rumah-tangga.webp"
  }'::jsonb
)
ON CONFLICT (id) DO NOTHING;
